In [1]:
import numpy as np

In [2]:
arr = ([4, 8 ,16])

In [3]:
arr

[4, 8, 16]

In [11]:
arr[0]

4

In [12]:
larr = np.array([[4,5,6],[1,2,3],[7,8,9]])

In [13]:
larr

array([[4, 5, 6],
       [1, 2, 3],
       [7, 8, 9]])

In [14]:
larr.dtype

dtype('int32')

In [15]:
larr.shape

(3, 3)

In [16]:
larr.size

9

In [17]:
np.array({3,6,9})

array({9, 3, 6}, dtype=object)

In [19]:
zeros = np.zeros((2,4))

In [20]:
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [23]:
zeros.dtype

dtype('float64')

In [24]:
rng = np.arange(5)

In [25]:
rng

array([0, 1, 2, 3, 4])

In [26]:
lspace = np.linspace(1,4,5)

In [27]:
lspace

array([1.  , 1.75, 2.5 , 3.25, 4.  ])

In [29]:
emp = np.empty((2,3))

In [30]:
emp

array([[0., 0., 0.],
       [0., 0., 0.]])

In [31]:
like = np.empty_like(lspace)

In [34]:
like

array([1.  , 1.75, 2.5 , 3.25, 4.  ])

In [35]:
identi = np.identity(40)

In [36]:
identi

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [43]:
raar = np.arange(101)

In [44]:
raar

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [49]:
a = [[1,2,3], [4,5,6],[7,8,9]]

In [50]:
ar = np.array(a)

In [51]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
ar.sum(axis=1)

array([ 6, 15, 24])

In [54]:
ar.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [56]:
ar.flat

In [57]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
8
9


In [58]:
ar.ndim

2

In [59]:
ar.nbytes

36

In [61]:
one = np.array([1,44,667,54])

In [63]:
one.argmax()

2

In [64]:
one.argmin()

0

In [65]:
one.argsort()

array([0, 1, 3, 2], dtype=int64)

In [66]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
ar.reshape((9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [69]:
ar2 = np.array([[1,3,5],
               [2,4,6],
               [7,8,9]])

In [70]:
ar + ar2

array([[ 2,  5,  8],
       [ 6,  9, 12],
       [14, 16, 18]])

In [72]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [73]:
ar.sum()

45

In [75]:
np.where(ar>6)

(array([2, 2, 2], dtype=int64), array([0, 1, 2], dtype=int64))

In [76]:
np.count_nonzero(ar)

9

In [77]:
import sys

In [80]:
py_ar = [0,6,66,7]

In [81]:
np_ar = np.array(py_ar)

In [82]:
sys.getsizeof(1) * len(py_ar)

112

In [83]:
np_ar.itemsize * np_ar.size

16

In [84]:
np_ar.tolist()

[0, 6, 66, 7]